<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Irene LiFeng Julià Pérez y Xisco Ribera Ramis">

<title>Normalidad Multivariante</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Normalidad_multivariante_files/libs/clipboard/clipboard.min.js"></script>
<script src="Normalidad_multivariante_files/libs/quarto-html/quarto.js"></script>
<script src="Normalidad_multivariante_files/libs/quarto-html/popper.min.js"></script>
<script src="Normalidad_multivariante_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Normalidad_multivariante_files/libs/quarto-html/anchor.min.js"></script>
<link href="Normalidad_multivariante_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Normalidad_multivariante_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Normalidad_multivariante_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Normalidad_multivariante_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Normalidad_multivariante_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Normalidad Multivariante</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Irene LiFeng Julià Pérez y Xisco Ribera Ramis </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="presentación-del-problema" class="level1">
<h1>Presentación del problema</h1>
<p>Vamos a tratar una base de datos relacionados con la cirrosis. La cirrosis es una etapa tardía de la cicatrización (fibrosis) del hígado causada por muchas formas de enfermedades y afecciones hepáticas, como la hepatitis y el alcoholismo crónico.</p>
<p>En este dataset tenemos 418 observaciones (pacientes) con 20 varibales:</p>
<p>Nuestro objetivo para este estudio sería:</p>
<ul>
<li>Comprobar si en nuestros datos hay normalidad multivariante.</li>
</ul>
<p>Los datos provienen de la página web Kaggle: <a href="https://www.kaggle.com/datasets/fedesoriano/cirrhosis-prediction-dataset/">Kaggle - Cirrhosis</a>.</p>
<p>El dataset consta de 418 muestras, donde cada una representa una serie de características de un paciente. A cada paciente se le atribuyen 26 valores, uno de ellos es su ID, y el resto son variables relacionadas con la salud cardíaca, tanto geográficas como de hábitos personales.</p>
<p>Antes de explicar cada variable, modifiquemos la tabla de datos para tenerla limpia en formato tidy.</p>
<p>Cargamos la librerías que utilizaremos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fmsb)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mvnormtest)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="convertir-los-datos-en-tidy" class="level1">
<h1>Convertir los datos en tidy</h1>
<p>Cargamos la tabla de datos y la convertimos a tibble para facilitarnos la manipulación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"cirrhosis.csv"</span>, <span class="at">header =</span> T)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> as.tibble</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [418 × 20] (S3: tbl_df/tbl/data.frame)
 $ ID           : int [1:418] 1 2 3 4 5 6 7 8 9 10 ...
 $ N_Days       : int [1:418] 400 4500 1012 1925 1504 2503 1832 2466 2400 51 ...
 $ Status       : chr [1:418] "D" "C" "D" "D" ...
 $ Drug         : chr [1:418] "D-penicillamine" "D-penicillamine" "D-penicillamine" "D-penicillamine" ...
 $ Age          : int [1:418] 21464 20617 25594 19994 13918 24201 20284 19379 15526 25772 ...
 $ Sex          : chr [1:418] "F" "F" "M" "F" ...
 $ Ascites      : chr [1:418] "Y" "N" "N" "N" ...
 $ Hepatomegaly : chr [1:418] "Y" "Y" "N" "Y" ...
 $ Spiders      : chr [1:418] "Y" "Y" "N" "Y" ...
 $ Edema        : chr [1:418] "Y" "N" "S" "S" ...
 $ Bilirubin    : num [1:418] 14.5 1.1 1.4 1.8 3.4 0.8 1 0.3 3.2 12.6 ...
 $ Cholesterol  : int [1:418] 261 302 176 244 279 248 322 280 562 200 ...
 $ Albumin      : num [1:418] 2.6 4.14 3.48 2.54 3.53 3.98 4.09 4 3.08 2.74 ...
 $ Copper       : int [1:418] 156 54 210 64 143 50 52 52 79 140 ...
 $ Alk_Phos     : num [1:418] 1718 7395 516 6122 671 ...
 $ SGOT         : num [1:418] 137.9 113.5 96.1 60.6 113.2 ...
 $ Tryglicerides: int [1:418] 172 88 55 92 72 63 213 189 88 143 ...
 $ Platelets    : int [1:418] 190 221 151 183 136 NA 204 373 251 302 ...
 $ Prothrombin  : num [1:418] 12.2 10.6 12 10.3 10.9 11 9.7 11 11 11.5 ...
 $ Stage        : int [1:418] 4 3 4 4 3 3 3 3 2 4 ...</code></pre>
</div>
</div>
<p>Vamos a modificar el data set para que sea más cómodo a la hora de trabajar con él.</p>
<p>Transformamos las variables qualitativas en factor y, en las de Si o No (Y: Si, N: No) cambiamos los valores para que sea más ilustrativa y entendible. De la misma forma con el sexo cromosómico (F: Female, M: Male)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Status =</span> <span class="fu">factor</span>(Status, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"C"</span>, <span class="st">"CL"</span>, <span class="st">"D"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Cens"</span>, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                                                      <span class="st">"Cens_Trat"</span>, <span class="st">"Muerto"</span>)))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Drug =</span> Drug <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">if_else</span>(Sex <span class="sc">==</span> <span class="st">"F"</span>, <span class="st">"Female"</span>, <span class="st">"Male"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Ascites =</span> <span class="fu">if_else</span>(Ascites <span class="sc">==</span> <span class="st">"Y"</span>, <span class="st">"Si"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Hepatomegaly =</span> <span class="fu">if_else</span>(Hepatomegaly <span class="sc">==</span> <span class="st">"Y"</span>, <span class="st">"Si"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Spiders =</span> <span class="fu">if_else</span>(Spiders <span class="sc">==</span> <span class="st">"Y"</span>, <span class="st">"Si"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Edema =</span> <span class="fu">factor</span>(Edema, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Y"</span>, <span class="st">"N"</span>, <span class="st">"S"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Si"</span>, <span class="st">"No"</span>,</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>                                                                     <span class="st">"Sin"</span>)))</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Stage =</span> Stage <span class="sc">%&gt;%</span> as.factor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Observemos que hay muestras que tienen valores desconocidos (NA). Veamos cuales son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 20
      ID N_Days Status Drug         Age Sex   Ascites Hepatomegaly Spiders Edema
   &lt;int&gt;  &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;      &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;        &lt;fct&gt;   &lt;fct&gt;
 1     6   2503 Muerto Placebo    24201 Fema… No      Si           No      No   
 2    14   1217 Muerto Placebo    20535 Male  Si      Si           No      Si   
 3    40   4467 Cens   D-penicil… 17046 Fema… No      No           No      No   
 4    41   1350 Muerto D-penicil… 12285 Fema… No      Si           No      No   
 5    42   4453 Cens   Placebo    12307 Fema… No      Si           Si      No   
 6    45   4025 Cens   Placebo    15265 Fema… No      No           No      No   
 7    49    708 Muerto Placebo    22336 Fema… No      Si           No      No   
 8    53   1000 Muerto D-penicil… 24621 Fema… No      Si           No      No   
 9    58   4459 Cens   D-penicil… 16279 Male  No      No           No      No   
10    70   3458 Cens   D-penicil… 20600 Fema… No      No           No      No   
# ℹ 132 more rows
# ℹ 10 more variables: Bilirubin &lt;dbl&gt;, Cholesterol &lt;int&gt;, Albumin &lt;dbl&gt;,
#   Copper &lt;int&gt;, Alk_Phos &lt;dbl&gt;, SGOT &lt;dbl&gt;, Tryglicerides &lt;int&gt;,
#   Platelets &lt;int&gt;, Prothrombin &lt;dbl&gt;, Stage &lt;fct&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>datos_na_omit <span class="ot">=</span> <span class="fu">na.omit</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El tibble resultante consta de 276 observaciones y 20 variables. Cada muestra representa un paciente al que se le ha extraido la siguiente información:</p>
<ul>
<li><code>ID</code>: Identificador único</li>
<li><code>N_Days</code>: Número de días entre el registro y la fecha de defunción, transplante o estudio analítico enJulio de 1986.</li>
<li><code>Status</code>: Estatus del paciente: C (Censurado), CL (censurado debido a tratamiento hepático), o D (Muerto)</li>
<li><code>Drug</code>: Tipo de fármaco: D-penicilamina o placebo</li>
<li><code>Age</code>: Edad [días]</li>
<li><code>Sex</code>: Sexo cromosómico: Male (hombre) o Female (Mujer)</li>
<li><code>Ascites</code>: Presencia de Ascitis No o Si</li>
<li><code>Hepatomegaly</code>: Presencia de Hepatomegalia No o Si</li>
<li><code>Spiders</code>: Presencia de arañas vasculares No o Si</li>
<li><code>Edema</code>: Presencia de Edema: No (no hay edema y sin tratamiento diurético para el edema), Sin (presencia de edema sin diuréticos, o edema curado con diuréticos), o Si (edema a pesar del tratamiento con diuréticos)</li>
<li><code>Bilirubin</code>: Bilirrubina sérica [mg/dl]</li>
<li><code>Cholesterol</code>: Colesterol sérico [mg/dl]</li>
<li><code>Albumin</code>: Albúmina [gm/dl]</li>
<li><code>Copper</code>: Cobre en orina [ug/day]</li>
<li><code>Alk_Phos</code>: Fosfatasa alcalina [U/liter]</li>
<li><code>SGOT</code>: SGOT [U/ml]</li>
<li><code>Triglycerides</code>: Triglicéridos [mg/dl]</li>
<li><code>Platelets</code>: Plaquetas por cúbico [ml/1000]</li>
<li><code>Prothrombin</code>: Tiempo de Protrombina [s]</li>
<li><code>Stage</code>: Estado histórico de la enfermedad (1, 2, 3, or 4)</li>
</ul>
</section>
<section id="análisis-multivariante" class="level1">
<h1>Análisis multivariante</h1>
<div class="cell" data-hash="Normalidad_multivariante_cache/html/unnamed-chunk-6_32ea10058ecc69fc6efc928d6efa63c1">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>datos_quant <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(datos_quant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análisis-de-normalidad-multivariante" class="level1">
<h1>Análisis de normalidad multivariante</h1>
<p>Vamos a extraer los datos cuantitativos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>datos_quant <span class="ot">=</span> datos_na_omit <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="dv">1</span>)  <span class="co"># id</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Con estos datos vamos a realizar nuestro estudio de normalidad multivariante.</p>
<p>Calculemos el vector de medias</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Medias <span class="ot">=</span> <span class="fu">colMeans</span>(datos_quant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>la matriz de covarianza:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> <span class="fu">cov</span>(datos_quant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>y la distancia de Mahalanobis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>d_Mahalanobis <span class="ot">=</span> <span class="fu">apply</span>(datos_quant, <span class="at">MARGIN =</span> <span class="dv">1</span>, <span class="cf">function</span>(x)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">t</span>(x <span class="sc">-</span> Medias)<span class="sc">%*%</span><span class="fu">solve</span>(S)<span class="sc">%*%</span>(x <span class="sc">-</span> Medias))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>d_Mahalanobis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 11.718462 15.647364  9.747850 15.183510  5.072358  8.960233  8.772232
  [8]  4.145256 13.765679  7.210558 15.589464  2.991863 18.426173  5.886979
 [15]  2.585319 42.565290  5.840747  7.378982  6.527884 26.898390 30.745499
 [22] 23.463103  6.646944 14.506722 31.508639 16.465003 12.998235 19.243242
 [29] 22.258913 13.245746 11.028889  5.764277 29.642003  5.672879 14.270163
 [36]  4.515420 26.377930 10.812091  7.995463 32.851781  5.119980 27.624049
 [43]  3.631690  4.420250  7.109662 11.474586 29.454388 49.488240 26.794818
 [50] 10.064439 14.551003 17.323207 18.163230 30.128045  6.429780  9.828907
 [57] 11.588981 24.203873  9.845456 16.565264  9.167816  8.557268  9.801214
 [64] 15.938393 62.890864  9.157143  6.605307  3.239670 10.174269 13.642506
 [71] 24.738868 17.351632 14.171342  6.392624  3.566705 43.742509 24.712613
 [78] 10.368774  2.219003  7.784229 17.860384 12.576723 12.584980  5.046221
 [85] 10.455438  7.355122  8.851012  8.562869  5.252602 10.129539  8.894670
 [92]  4.102221  5.211776 56.422462  4.047849  2.706426  4.613880 10.273413
 [99]  9.019210  3.056667 10.925719  4.199308 26.086996  8.245671  2.179204
[106]  9.113117 27.709243 14.723106  4.540474  3.940107  1.758935  6.829521
[113] 50.543750 13.430920  5.131718  7.062881  5.753893  8.624034  4.680699
[120]  5.866327  7.285545  5.398240  7.515726  3.013303  2.860935  2.749663
[127] 51.792476  4.268320  9.112389 16.203558 13.463033  8.706250 11.945352
[134]  3.263784 21.565567  4.106643 35.362647 10.414131  4.316046  4.196678
[141]  2.776266  4.541768  6.035805  5.559548  2.829745 57.968918  6.727446
[148]  7.332535  5.767668  2.638952 14.250381  4.261564  3.826232  1.625473
[155] 13.835275  6.472582  7.155574 20.042637  1.979061  8.969852 11.903706
[162]  3.650101  1.829659 52.542164  3.613559 12.504660  7.924428 11.968691
[169]  5.408861  2.851939 10.727599  6.231714  5.978860  3.812190 12.336955
[176] 13.444837  4.333236 11.318757  5.492118  5.329964  1.638542  3.346765
[183]  3.844268  9.933024 20.871767  8.319631  6.423129  6.181477  3.132789
[190]  7.120091 13.407470  3.071385  2.585455  3.296180 10.134940  6.046290
[197]  6.392273  9.954989 19.173175  3.628308 26.417709  8.070163 27.917038
[204]  3.685407  6.288423  9.183474  3.882853 19.160820  8.889665  8.908688
[211] 15.109586  6.286972  6.940399 42.979239  3.811287  4.132743  8.623771
[218]  2.925949  6.173878 21.967841  4.938974  7.289850  5.233692  7.657745
[225]  3.480926  5.275402  8.059528  7.417159  7.603438  4.791384  2.660594
[232]  9.710925 12.777153  9.345158  5.657538  8.466416  2.899031 10.347661
[239]  2.935390  4.951773  6.278459  6.095908  6.917207  5.098721  3.089117
[246] 36.269275  6.329565 10.531152  4.545608  3.297354  4.827752  2.756816
[253]  9.698204 13.397437  6.160833  6.906080  3.452027  7.379417 11.188089
[260]  7.543890  6.499234  4.270344  1.967815  3.588997  2.581861  5.947847
[267]  3.860676  7.903101 16.276425  3.780733  7.660485  4.133441  7.163881
[274]  6.072264  6.423367  7.078246</code></pre>
</div>
</div>
<p>Una vez calculadas estas medidas, representemos los datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">qchisq</span>((<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(datos_quant) <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">nrow</span>(datos_quant), <span class="at">df =</span> <span class="dv">3</span>), <span class="fu">sort</span>(d_Mahalanobis), <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Cuantiles de la "</span>, chi[<span class="dv">20</span>]<span class="sc">^</span><span class="dv">2</span>)),<span class="at">ylab=</span><span class="st">"Distancias ordenadas"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">0</span>,<span class="at">b=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vamos a realizar un test de normalidad. Utilizaremos Shapiro-Wilk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mvnormtest<span class="sc">::</span><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(datos_quant))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.83366, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Obtenemos un p-valor muy pequeño, prácticamente 0, entonces, rechazamos la hipótesis nula y concluimos que no hay normalidad multivariante, es decir, almenos una variable individual no se distribuye normalmente.</p>
<p>Veamos una por una si se distribuyen normalmente. Aplicaremos a cada variable el el test de Shapiro Wilks, siempre y cuando haya pocos datos repetidos, ya que es sensible a este hecho.</p>
<ul>
<li><code>N-days</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>N_Days, <span class="at">main =</span> <span class="st">"N_days"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38 30</code></pre>
</div>
</div>
<p>Observemos que en las colas encontramos muchas muestras que se salen de las bandas de confianza, por tanto es un indicador que de questa variable no siga una normal. Corroboremoslo con un test.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>N_Days)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>N_Days))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>N_Days)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 276</code></pre>
</div>
</div>
<p>Notemos que hay datos repetidos, por realicemos unos cuantos tests de normalidad.</p>
<pre><code>- Shapiro:</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_quant<span class="sc">$</span>N_Days)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_quant$N_Days
W = 0.9707, p-value = 1.985e-05</code></pre>
</div>
</div>
<p>Nos ha salido un p-value = 1.985e-05, bastante pequeño, con lo quepodemos rechazar la normalidad de esta variable.</p>
<pre><code>- Anderson-Darling</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(datos_quant<span class="sc">$</span>N_Days)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  datos_quant$N_Days
A = 1.9897, p-value = 4.437e-05</code></pre>
</div>
</div>
<p>Nos ha salido un p-value = 4.437e-05, bastante pequeño, con lo que también podemos rechazar la normalidad de esta variable.</p>
<p>Por tanto podemos concluir que la variable <code>N_Days</code> no sigue una distribución normal</p>
<ul>
<li><code>Age</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Age, <span class="at">main =</span> <span class="st">"Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 220  82</code></pre>
</div>
</div>
<p>Observemos que en las colas encontramos algunas muestras que se salen de las bandas de confianza, por tanto a simple vista no podemos asegurar nada.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Age)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Hay 1 valor que se repite, por tanto, podemos aplicar el shapiro test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_quant<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_quant$Age
W = 0.9907, p-value = 0.07685</code></pre>
</div>
</div>
<p>Nos ha salido un p-value = 0.07685, por tanto estamos en la zona de penumbra y no podemos concluir nada. Necesitaríamos más datos para poder asegurar o negar la normalidad.</p>
<p>Realicemos otro test de normalidad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(datos_quant<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  datos_quant$Age
A = 0.47535, p-value = 0.238</code></pre>
</div>
</div>
<p>Con el test de Anderson-Darling nos sale un p-value = 0.238 y con este test podríamosasegurar la normalidad, aunque nosotros cogeremos esta concluisión con pinzas.</p>
<ul>
<li><code>Bilirubin</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Bilirubin, <span class="at">main =</span> <span class="st">"Bilirubin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127 137</code></pre>
</div>
</div>
<p>Observemos que claramente no seguirá una normal debido a que no hay casi ninguna observación dentro de las bandas de confianza. Respaldemos esta afermación con un test.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Bilirubin)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Bilirubin))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 194</code></pre>
</div>
</div>
<p>Hay 194 valores que se repiten, por tanto, no podemos aplicar el shapiro test. En su lugar apliquemos un test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Bilirubin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 184.3264
    Z3  | Skewness: 11.3328
    Z4  | Kurtosis: 7.4762
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 7.638e-14 </code></pre>
</div>
</div>
<p>Nos ha salido un p-value &lt; 2.2e-16 en los tres tests, podemos rechazar la normalidad de esta variable, resultado que esperábamos con el qqplot.</p>
<ul>
<li><code>Cholesterol</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Cholesterol, <span class="at">main =</span> <span class="st">"Cholesterol"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 113 214</code></pre>
</div>
</div>
<p>Observemos que en esta variable ocurre lo mismo que con la anterior (<code>Bilirubin</code>).</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Cholesterol)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Cholesterol))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78</code></pre>
</div>
</div>
<p>Volvemos a tener muchos datos repetidos, por tanto aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Cholesterol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 222.421
    Z3  | Skewness: 12.2849
    Z4  | Kurtosis: 8.4558
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: &lt; 2.2e-16 </code></pre>
</div>
</div>
<p>Nos ha salido un p-value &lt; 2.2e-16 en los tres tests, podemos rechazar la normalidad de esta variable, resultado que volvíamos a esperábamos con el qqplot.</p>
<ul>
<li><code>Albumin</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Albumin, <span class="at">main =</span> <span class="st">"Albumin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 199 246</code></pre>
</div>
</div>
<p>Volvemos a observar que seguramente no seguirá una distribución normal debido a las observaciones que hay fuera de las bandas.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Albumin)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Albumin))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 151</code></pre>
</div>
</div>
<p>Volvemos a tener muchos datos repetidos, por tanto aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Albumin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 20.7075
    Z3  | Skewness: -3.8537
    Z4  | Kurtosis: 2.4201
  P VALUE:
    Omnibus  Test: 3.187e-05 
    Skewness Test: 0.0001164 
    Kurtosis Test: 0.01552 </code></pre>
</div>
</div>
<p>En este caso, los tres p-values son menores que 0.05, por tanto rechazamos la normalidad de esta variable.</p>
<ul>
<li><code>Copper</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Copper, <span class="at">main =</span> <span class="st">"Copper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16 21</code></pre>
</div>
</div>
<p>Volvemos a observar que esta muestra no seguirá una distribución normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Copper)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Copper))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 124</code></pre>
</div>
</div>
<p>Como volvemos a tener muchos datos repetidos, aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Copper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 150.0913
    Z3  | Skewness: 10.0613
    Z4  | Kurtosis: 6.9901
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 2.747e-12 </code></pre>
</div>
</div>
<p>Nos vuelven a salir un p-value bastante pequeño, con lo que volvemos a rechazar la normalidad de esta variable.</p>
<ul>
<li><code>Alk_Phos</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Alk_Phos, <span class="at">main =</span> <span class="st">"Alk_Phos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48 33</code></pre>
</div>
</div>
<p>Tampoco seguirá una distribución normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Alk_Phos)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Alk_Phos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
</div>
<p>No hay muchos datos repetido. Probemos de hacer un shapiro test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_quant<span class="sc">$</span>Alk_Phos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_quant$Alk_Phos
W = 0.62114, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Nos sale un p-value &lt; 2.2e-16 por tanto rechazaríamos la normalidad de esta variable. Reforcemos esta afirmación realizando un test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Alk_Phos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 197.5003
    Z3  | Skewness: 11.7012
    Z4  | Kurtosis: 7.7835
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 7.105e-15 </code></pre>
</div>
</div>
<p>Efectivamente la variable no sigue una distribución normal.</p>
<ul>
<li><code>SGOT</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>SGOT, <span class="at">main =</span> <span class="st">"SGOT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 146 246</code></pre>
</div>
</div>
<p>Observemos que encontramos algunas observaciones fuera de las bandas de confianza, lo que indica que tampoco será normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>SGOT)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>SGOT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 110</code></pre>
</div>
</div>
<p>Como volvemos a tener muchos datos repetidos, aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>SGOT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 95.1947
    Z3  | Skewness: 7.7563
    Z4  | Kurtosis: 5.919
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: 8.66e-15 
    Kurtosis Test: 3.24e-09 </code></pre>
</div>
</div>
<p>Podemos concluir que esta variable tampoco sigue una distribución normal.</p>
<ul>
<li><code>Tryglicerides</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Tryglicerides, <span class="at">main =</span> <span class="st">"Tryglicerides"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Normalidad_multivariante_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  65 164</code></pre>
</div>
</div>
<p>El resultado no es diferente a la de las otras variables. Confirmemos que no sigue una normal.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>